import React, { useState } from "react";
import { Sparkles, BarChart3, RefreshCw, CheckCircle2, Target, Zap } from "lucide-react";
import { ai } from "@/lib/ai";
import { Button } from "@/components/ui/Button";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/Card";
import { AIStatus } from "@/components/ai/AIStatus";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface WeeklySummaryCardProps {
  sessions: any[];
  logs: any[];
}

export const WeeklySummaryCard: React.FC<WeeklySummaryCardProps> = ({ sessions, logs }) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [isThinking, setIsThinking] = useState(false);

  const generateSummary = async () => {
    if (!ai.isConfigured) return;
    setIsThinking(true);
    try {
      const result = await ai.generateWeeklySummary({ sessions, logs });
      setSummary(result);
    } catch (err) {
      console.error(err);
    } finally {
      setIsThinking(false);
    }
  };

  return (
    <Card className="bg-surface/30 border-border/10 backdrop-blur-3xl overflow-hidden shadow-2xl group hover:border-amber/20 transition-all duration-500">
      <CardHeader className="border-b border-border/5 pb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
             <div className="p-2 bg-amber/10 rounded-xl">
               <Sparkles className="h-4 w-4 text-amber" />
             </div>
             <div>
               <CardTitle className="text-sm font-black uppercase tracking-widest flex items-center gap-2">
                 AI Ship Report
               </CardTitle>
               <CardDescription className="text-[10px] font-bold text-mist/40 uppercase tracking-widest">Weekly Project Synthesis</CardDescription>
             </div>
          </div>
          <Button 
            onClick={generateSummary} 
            disabled={isThinking}
            variant="ghost" 
            size="icon" 
            className="h-8 w-8 text-mist hover:text-amber"
          >
            <RefreshCw className={`h-4 w-4 ${isThinking ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </CardHeader>
      
      <CardContent className="pt-6">
        {summary ? (
          <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-700">
            <div className="prose prose-invert prose-xs max-w-none text-mist leading-relaxed font-medium selection:bg-amber selection:text-ink">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {summary}
              </ReactMarkdown>
            </div>
            <div className="pt-4 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-amber/40">
              <Zap className="h-3 w-3" />
              Generated by Bloc Intelligence
            </div>
          </div>
        ) : (
          <div className="py-12 flex flex-col items-center justify-center text-center space-y-4">
            <div className="h-16 w-16 rounded-full bg-surface2/50 flex items-center justify-center border border-border/5 mb-2 group-hover:scale-110 transition-transform duration-500">
               <BarChart3 className="h-6 w-6 text-mist/20" />
            </div>
            <div>
              <h4 className="text-xs font-black text-chalk uppercase tracking-widest mb-1">Weekly Reflection Ready</h4>
              <p className="text-[10px] text-mist/40 font-medium max-w-[180px] mx-auto uppercase tracking-widest leading-relaxed">
                Analyze your last 7 days of ship logs and focus sessions.
              </p>
            </div>
            <Button 
              onClick={generateSummary} 
              disabled={isThinking}
              className="bg-amber hover:bg-amber/90 text-ink h-10 px-6 font-black uppercase tracking-widest text-[10px] shadow-xl shadow-amber/10 gap-2"
            >
              {isThinking ? "Synthesizing..." : "Generate Report"} <Sparkles className="h-3 w-3" />
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
